In [19]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from pandas.plotting import scatter_matrix 
import matplotlib.pyplot as plt 
from sklearn import model_selection 
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.neighbors import KNeighborsClassifier 
import datetime

from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures

In [20]:
train = pd.read_csv("Computers2.csv")
train.describe()

             price        speed           hd          ram       screen
count  1499.000000  1499.000000  1499.000000  1499.000000  1499.000000
mean   2369.602402    44.272849   269.726484     7.012675    14.422949
std     624.745680    15.371010   150.546512     4.258249     0.787863
min     999.000000    25.000000    80.000000     2.000000    14.000000
25%    1899.000000    33.000000   170.000000     4.000000    14.000000
50%    2295.000000    33.000000   245.000000     8.000000    14.000000
75%    2720.000000    66.000000   340.000000     8.000000    15.000000
max    4999.000000    66.000000  1370.000000    16.000000    17.000000

In [21]:
feature_names = ['speed','hd','ram','screen','cd','premium']

In [22]:
data = pd.DataFrame()

In [23]:
prem={'yes':1,'no':0}
cd_c={'yes':1,'no':0}
def clean_prem(x):
    return prem[x]
def clean_cd_c(x):
    return cd_c[x]
data['price']=train['price']
data['speed']=train['speed']
data['hd']=train['hd']
data['ram']=train['ram']
data['screen']=train['screen']
data['cd']=train['cd'].apply(clean_cd_c)
data['premium']=train['premium'].apply(clean_prem)

In [24]:
data.head()

   price  speed   hd  ram  screen  cd  premium
0   1499     25   80    4      14   0        1
1   1795     33   85    2      14   0        1
2   1595     25  170    4      15   0        1
3   1849     25  170    8      14   0        0
4   3295     33  340   16      14   0        1

In [25]:
X = data[feature_names]
X

      speed   hd  ram  screen  cd  premium
0        25   80    4      14   0        1
1        33   85    2      14   0        1
2        25  170    4      15   0        1
3        25  170    8      14   0        0
4        33  340   16      14   0        1
...     ...  ...  ...     ...  ..      ...
1494     50  107    2      14   0        1
1495     33  528   16      15   0        1
1496     50  528   16      14   0        1
1497     33  120    4      14   0        0
1498     33  210    4      15   0        1

[1499 rows x 6 columns]

In [26]:
y = data.price
print(y)

0       1499
1       1795
2       1595
3       1849
4       3295
        ...
1494    1944
1495    2690
1496    2895
1497    2029
1498    1699
Name: price, Length: 1499, dtype: int64

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=20)

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge,Lasso
#from sklearn.ensemble import AdaBoostRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
#from sklearn.ensemble import GradientBoostingRegressor
#import xgboost as xgb
#from xgboost.sklearn import XGBRegressor
from sklearn.metrics import r2_score
#print("R2 score : %.2f" % r2_score(dtesty,prediction))
m=list()
m.append(["LinearRegression",LinearRegression()])
m.append(["Ridge",Ridge()])
m.append(["Lasso",Lasso()])
m.append(["LogisticRegressor",LogisticRegression()])
#m.append(["AdaBoostRegressor",AdaBoostRegressor()])
m.append(["ExtraTreesRegressor",ExtraTreesRegressor()])
m.append(["DecisionTreeRegressor",DecisionTreeRegressor()])
m.append(["RandomForestRegressor",RandomForestRegressor()])
#m.append(["GradientBoostingRegressor",GradientBoostingRegressor()])
#r=list()
for name,model in m:
    model.fit(X_train,y_train)
    prediction = model.predict(X_test)
    #r.append(eval("%.2f" % r2_score(test_Y,prediction)))
    r2score=eval("%.2f" % r2_score(y_test,prediction))
    raw_data=np.sqrt(mean_squared_error(y_test,prediction))
    print(name,":\n\tr2 score: ",r2score,"\n\trmse:",raw_data)

LinearRegression :
	r2 score:  0.75
	rmse: 294.07250392320225
Ridge :
	r2 score:  0.75
	rmse: 294.04824927267805
Lasso :
	r2 score:  0.75
	rmse: 293.99459090503365

c:\users\personal\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\personal\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

LogisticRegressor :
	r2 score:  0.5
	rmse: 417.69865533260537
ExtraTreesRegressor :
	r2 score:  0.9
	rmse: 187.68073218964273
DecisionTreeRegressor :
	r2 score:  0.89
	rmse: 198.7045889132783
RandomForestRegressor :
	r2 score:  0.9
	rmse: 188.0689153423441

c:\users\personal\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\personal\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [32]:
naming=['speed','hd','ram','screen','cd','premium']
B=[]
print("ENTER VALUE FOR\n")
for i in naming:
  print(i)
  B.append(input())
X_value=np.reshape(B,(1, -1))
getresult=ExtraTreesRegressor()
getresult.fit(X_train,y_train)
predictions=getresult.predict(X_value)
print("Computer Price:\r")
print(predictions.astype('int'))

ENTER VALUE FOR

speed
25
hd
80
ram
4
screen
14
cd
0
premium
1
Computer Price:
[1397]

c:\users\personal\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)